/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

/**
 *
 * @author Dario
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    double operando1 = 0; //guarda el primer numero que metemos
    String operacion = ""; //guarda la operacion usada
    
    
    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pantalla = new javax.swing.JLabel();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonsuma = new javax.swing.JButton();
        botonigual = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pantalla.setForeground(new java.awt.Color(51, 255, 0));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pantalla.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 431, 76));

        boton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        getContentPane().add(boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, 64, 64));

        boton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        getContentPane().add(boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 107, 64, 64));

        boton9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        getContentPane().add(boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 107, 64, 64));

        boton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        getContentPane().add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 189, 64, 64));

        boton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        getContentPane().add(boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 189, 64, 64));

        boton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        getContentPane().add(boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 189, 64, 64));

        boton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 281, 64, 64));

        boton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 281, 64, 64));

        boton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        getContentPane().add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 281, 64, 64));

        boton0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        getContentPane().add(boton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 363, 64, 64));

        botonsuma.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botonsuma.setText("+");
        botonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumaActionPerformed(evt);
            }
        });
        getContentPane().add(botonsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 107, 80, 70));

        botonigual.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botonigual.setText("=");
        botonigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonigualActionPerformed(evt);
            }
        });
        getContentPane().add(botonigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "7");
        }
        else{ 
            pantalla.setText(auxiliar + "7");
        }
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "8");
        }
        else{ 
            pantalla.setText(auxiliar + "8");
        }
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "9");
        }
        else{ 
            pantalla.setText(auxiliar + "9");
        }
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "4");
        }
        else{ 
            pantalla.setText(auxiliar + "4");
        }
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "5");
        }
        else{ 
            pantalla.setText(auxiliar + "5");
        }
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "6");
        }
        else{ 
            pantalla.setText(auxiliar + "6");
        }
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "1");
        }
        else{ 
            pantalla.setText(auxiliar + "1");
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "2");
        }
        else{ 
            pantalla.setText(auxiliar + "2");
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "3");
        }
        else{ 
            pantalla.setText(auxiliar + "3");
        }
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText(auxiliar + "0");
        }
        else{ 
            pantalla.setText(auxiliar + "0");
        }
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumaActionPerformed
        operacion = "+";
        //Double.valueof convierte un strieng
        //en su equivalete numerico
        operando1 = Double.valueOf(pantalla.getText());
        //reseteo pantalla
        pantalla.setText("0");
        
    }//GEN-LAST:event_botonsumaActionPerformed

    private void botonigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonigualActionPerformed
        double operando2 = Double.valueOf(pantalla.getText());
        if (operacion.equals("+")){
            operando1 = operando1 + operando2;
        }
        
        pantalla.setText(""+operando1);
    }//GEN-LAST:event_botonigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonigual;
    private javax.swing.JButton botonsuma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
